/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as KomikRouteImport } from './routes/komik'
import { Route as Anime2RouteImport } from './routes/anime2'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KomikIndexRouteImport } from './routes/komik.index'
import { Route as Anime2IndexRouteImport } from './routes/anime2.index'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as KomikSearchRouteImport } from './routes/komik.search'
import { Route as Anime2SearchRouteImport } from './routes/anime2.search'
import { Route as AnimeSearchRouteImport } from './routes/anime.search'
import { Route as KomikDetailSlugRouteImport } from './routes/komik.detail.$slug'
import { Route as KomikChapterSlugRouteImport } from './routes/komik.chapter.$slug'
import { Route as KomikCategoryPageRouteImport } from './routes/komik.$category.$page'
import { Route as Anime2WatchSlugRouteImport } from './routes/anime2.watch.$slug'
import { Route as Anime2OngoingAnimePageRouteImport } from './routes/anime2.ongoing-anime.$page'
import { Route as Anime2DetailSlugRouteImport } from './routes/anime2.detail.$slug'
import { Route as Anime2CompleteAnimePageRouteImport } from './routes/anime2.complete-anime.$page'
import { Route as AnimeWatchSlugRouteImport } from './routes/anime.watch.$slug'
import { Route as AnimeOngoingAnimePageRouteImport } from './routes/anime.ongoing-anime.$page'
import { Route as AnimeDetailSlugRouteImport } from './routes/anime.detail.$slug'
import { Route as AnimeCompleteAnimePageRouteImport } from './routes/anime.complete-anime.$page'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikRoute = KomikRouteImport.update({
  id: '/komik',
  path: '/komik',
  getParentRoute: () => rootRouteImport,
} as any)
const Anime2Route = Anime2RouteImport.update({
  id: '/anime2',
  path: '/anime2',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KomikIndexRoute = KomikIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KomikRoute,
} as any)
const Anime2IndexRoute = Anime2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Anime2Route,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimeRoute,
} as any)
const KomikSearchRoute = KomikSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => KomikRoute,
} as any)
const Anime2SearchRoute = Anime2SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => Anime2Route,
} as any)
const AnimeSearchRoute = AnimeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AnimeRoute,
} as any)
const KomikDetailSlugRoute = KomikDetailSlugRouteImport.update({
  id: '/detail/$slug',
  path: '/detail/$slug',
  getParentRoute: () => KomikRoute,
} as any)
const KomikChapterSlugRoute = KomikChapterSlugRouteImport.update({
  id: '/chapter/$slug',
  path: '/chapter/$slug',
  getParentRoute: () => KomikRoute,
} as any)
const KomikCategoryPageRoute = KomikCategoryPageRouteImport.update({
  id: '/$category/$page',
  path: '/$category/$page',
  getParentRoute: () => KomikRoute,
} as any)
const Anime2WatchSlugRoute = Anime2WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => Anime2Route,
} as any)
const Anime2OngoingAnimePageRoute = Anime2OngoingAnimePageRouteImport.update({
  id: '/ongoing-anime/$page',
  path: '/ongoing-anime/$page',
  getParentRoute: () => Anime2Route,
} as any)
const Anime2DetailSlugRoute = Anime2DetailSlugRouteImport.update({
  id: '/detail/$slug',
  path: '/detail/$slug',
  getParentRoute: () => Anime2Route,
} as any)
const Anime2CompleteAnimePageRoute = Anime2CompleteAnimePageRouteImport.update({
  id: '/complete-anime/$page',
  path: '/complete-anime/$page',
  getParentRoute: () => Anime2Route,
} as any)
const AnimeWatchSlugRoute = AnimeWatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeOngoingAnimePageRoute = AnimeOngoingAnimePageRouteImport.update({
  id: '/ongoing-anime/$page',
  path: '/ongoing-anime/$page',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeDetailSlugRoute = AnimeDetailSlugRouteImport.update({
  id: '/detail/$slug',
  path: '/detail/$slug',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeCompleteAnimePageRoute = AnimeCompleteAnimePageRouteImport.update({
  id: '/complete-anime/$page',
  path: '/complete-anime/$page',
  getParentRoute: () => AnimeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/anime2': typeof Anime2RouteWithChildren
  '/komik': typeof KomikRouteWithChildren
  '/project': typeof ProjectRoute
  '/settings': typeof SettingsRoute
  '/anime/search': typeof AnimeSearchRoute
  '/anime2/search': typeof Anime2SearchRoute
  '/komik/search': typeof KomikSearchRoute
  '/anime/': typeof AnimeIndexRoute
  '/anime2/': typeof Anime2IndexRoute
  '/komik/': typeof KomikIndexRoute
  '/anime/complete-anime/$page': typeof AnimeCompleteAnimePageRoute
  '/anime/detail/$slug': typeof AnimeDetailSlugRoute
  '/anime/ongoing-anime/$page': typeof AnimeOngoingAnimePageRoute
  '/anime/watch/$slug': typeof AnimeWatchSlugRoute
  '/anime2/complete-anime/$page': typeof Anime2CompleteAnimePageRoute
  '/anime2/detail/$slug': typeof Anime2DetailSlugRoute
  '/anime2/ongoing-anime/$page': typeof Anime2OngoingAnimePageRoute
  '/anime2/watch/$slug': typeof Anime2WatchSlugRoute
  '/komik/$category/$page': typeof KomikCategoryPageRoute
  '/komik/chapter/$slug': typeof KomikChapterSlugRoute
  '/komik/detail/$slug': typeof KomikDetailSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project': typeof ProjectRoute
  '/settings': typeof SettingsRoute
  '/anime/search': typeof AnimeSearchRoute
  '/anime2/search': typeof Anime2SearchRoute
  '/komik/search': typeof KomikSearchRoute
  '/anime': typeof AnimeIndexRoute
  '/anime2': typeof Anime2IndexRoute
  '/komik': typeof KomikIndexRoute
  '/anime/complete-anime/$page': typeof AnimeCompleteAnimePageRoute
  '/anime/detail/$slug': typeof AnimeDetailSlugRoute
  '/anime/ongoing-anime/$page': typeof AnimeOngoingAnimePageRoute
  '/anime/watch/$slug': typeof AnimeWatchSlugRoute
  '/anime2/complete-anime/$page': typeof Anime2CompleteAnimePageRoute
  '/anime2/detail/$slug': typeof Anime2DetailSlugRoute
  '/anime2/ongoing-anime/$page': typeof Anime2OngoingAnimePageRoute
  '/anime2/watch/$slug': typeof Anime2WatchSlugRoute
  '/komik/$category/$page': typeof KomikCategoryPageRoute
  '/komik/chapter/$slug': typeof KomikChapterSlugRoute
  '/komik/detail/$slug': typeof KomikDetailSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/anime2': typeof Anime2RouteWithChildren
  '/komik': typeof KomikRouteWithChildren
  '/project': typeof ProjectRoute
  '/settings': typeof SettingsRoute
  '/anime/search': typeof AnimeSearchRoute
  '/anime2/search': typeof Anime2SearchRoute
  '/komik/search': typeof KomikSearchRoute
  '/anime/': typeof AnimeIndexRoute
  '/anime2/': typeof Anime2IndexRoute
  '/komik/': typeof KomikIndexRoute
  '/anime/complete-anime/$page': typeof AnimeCompleteAnimePageRoute
  '/anime/detail/$slug': typeof AnimeDetailSlugRoute
  '/anime/ongoing-anime/$page': typeof AnimeOngoingAnimePageRoute
  '/anime/watch/$slug': typeof AnimeWatchSlugRoute
  '/anime2/complete-anime/$page': typeof Anime2CompleteAnimePageRoute
  '/anime2/detail/$slug': typeof Anime2DetailSlugRoute
  '/anime2/ongoing-anime/$page': typeof Anime2OngoingAnimePageRoute
  '/anime2/watch/$slug': typeof Anime2WatchSlugRoute
  '/komik/$category/$page': typeof KomikCategoryPageRoute
  '/komik/chapter/$slug': typeof KomikChapterSlugRoute
  '/komik/detail/$slug': typeof KomikDetailSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/anime2'
    | '/komik'
    | '/project'
    | '/settings'
    | '/anime/search'
    | '/anime2/search'
    | '/komik/search'
    | '/anime/'
    | '/anime2/'
    | '/komik/'
    | '/anime/complete-anime/$page'
    | '/anime/detail/$slug'
    | '/anime/ongoing-anime/$page'
    | '/anime/watch/$slug'
    | '/anime2/complete-anime/$page'
    | '/anime2/detail/$slug'
    | '/anime2/ongoing-anime/$page'
    | '/anime2/watch/$slug'
    | '/komik/$category/$page'
    | '/komik/chapter/$slug'
    | '/komik/detail/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project'
    | '/settings'
    | '/anime/search'
    | '/anime2/search'
    | '/komik/search'
    | '/anime'
    | '/anime2'
    | '/komik'
    | '/anime/complete-anime/$page'
    | '/anime/detail/$slug'
    | '/anime/ongoing-anime/$page'
    | '/anime/watch/$slug'
    | '/anime2/complete-anime/$page'
    | '/anime2/detail/$slug'
    | '/anime2/ongoing-anime/$page'
    | '/anime2/watch/$slug'
    | '/komik/$category/$page'
    | '/komik/chapter/$slug'
    | '/komik/detail/$slug'
  id:
    | '__root__'
    | '/'
    | '/anime'
    | '/anime2'
    | '/komik'
    | '/project'
    | '/settings'
    | '/anime/search'
    | '/anime2/search'
    | '/komik/search'
    | '/anime/'
    | '/anime2/'
    | '/komik/'
    | '/anime/complete-anime/$page'
    | '/anime/detail/$slug'
    | '/anime/ongoing-anime/$page'
    | '/anime/watch/$slug'
    | '/anime2/complete-anime/$page'
    | '/anime2/detail/$slug'
    | '/anime2/ongoing-anime/$page'
    | '/anime2/watch/$slug'
    | '/komik/$category/$page'
    | '/komik/chapter/$slug'
    | '/komik/detail/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnimeRoute: typeof AnimeRouteWithChildren
  Anime2Route: typeof Anime2RouteWithChildren
  KomikRoute: typeof KomikRouteWithChildren
  ProjectRoute: typeof ProjectRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik': {
      id: '/komik'
      path: '/komik'
      fullPath: '/komik'
      preLoaderRoute: typeof KomikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime2': {
      id: '/anime2'
      path: '/anime2'
      fullPath: '/anime2'
      preLoaderRoute: typeof Anime2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komik/': {
      id: '/komik/'
      path: '/'
      fullPath: '/komik/'
      preLoaderRoute: typeof KomikIndexRouteImport
      parentRoute: typeof KomikRoute
    }
    '/anime2/': {
      id: '/anime2/'
      path: '/'
      fullPath: '/anime2/'
      preLoaderRoute: typeof Anime2IndexRouteImport
      parentRoute: typeof Anime2Route
    }
    '/anime/': {
      id: '/anime/'
      path: '/'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/komik/search': {
      id: '/komik/search'
      path: '/search'
      fullPath: '/komik/search'
      preLoaderRoute: typeof KomikSearchRouteImport
      parentRoute: typeof KomikRoute
    }
    '/anime2/search': {
      id: '/anime2/search'
      path: '/search'
      fullPath: '/anime2/search'
      preLoaderRoute: typeof Anime2SearchRouteImport
      parentRoute: typeof Anime2Route
    }
    '/anime/search': {
      id: '/anime/search'
      path: '/search'
      fullPath: '/anime/search'
      preLoaderRoute: typeof AnimeSearchRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/komik/detail/$slug': {
      id: '/komik/detail/$slug'
      path: '/detail/$slug'
      fullPath: '/komik/detail/$slug'
      preLoaderRoute: typeof KomikDetailSlugRouteImport
      parentRoute: typeof KomikRoute
    }
    '/komik/chapter/$slug': {
      id: '/komik/chapter/$slug'
      path: '/chapter/$slug'
      fullPath: '/komik/chapter/$slug'
      preLoaderRoute: typeof KomikChapterSlugRouteImport
      parentRoute: typeof KomikRoute
    }
    '/komik/$category/$page': {
      id: '/komik/$category/$page'
      path: '/$category/$page'
      fullPath: '/komik/$category/$page'
      preLoaderRoute: typeof KomikCategoryPageRouteImport
      parentRoute: typeof KomikRoute
    }
    '/anime2/watch/$slug': {
      id: '/anime2/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/anime2/watch/$slug'
      preLoaderRoute: typeof Anime2WatchSlugRouteImport
      parentRoute: typeof Anime2Route
    }
    '/anime2/ongoing-anime/$page': {
      id: '/anime2/ongoing-anime/$page'
      path: '/ongoing-anime/$page'
      fullPath: '/anime2/ongoing-anime/$page'
      preLoaderRoute: typeof Anime2OngoingAnimePageRouteImport
      parentRoute: typeof Anime2Route
    }
    '/anime2/detail/$slug': {
      id: '/anime2/detail/$slug'
      path: '/detail/$slug'
      fullPath: '/anime2/detail/$slug'
      preLoaderRoute: typeof Anime2DetailSlugRouteImport
      parentRoute: typeof Anime2Route
    }
    '/anime2/complete-anime/$page': {
      id: '/anime2/complete-anime/$page'
      path: '/complete-anime/$page'
      fullPath: '/anime2/complete-anime/$page'
      preLoaderRoute: typeof Anime2CompleteAnimePageRouteImport
      parentRoute: typeof Anime2Route
    }
    '/anime/watch/$slug': {
      id: '/anime/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/anime/watch/$slug'
      preLoaderRoute: typeof AnimeWatchSlugRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/ongoing-anime/$page': {
      id: '/anime/ongoing-anime/$page'
      path: '/ongoing-anime/$page'
      fullPath: '/anime/ongoing-anime/$page'
      preLoaderRoute: typeof AnimeOngoingAnimePageRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/detail/$slug': {
      id: '/anime/detail/$slug'
      path: '/detail/$slug'
      fullPath: '/anime/detail/$slug'
      preLoaderRoute: typeof AnimeDetailSlugRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/complete-anime/$page': {
      id: '/anime/complete-anime/$page'
      path: '/complete-anime/$page'
      fullPath: '/anime/complete-anime/$page'
      preLoaderRoute: typeof AnimeCompleteAnimePageRouteImport
      parentRoute: typeof AnimeRoute
    }
  }
}

interface AnimeRouteChildren {
  AnimeSearchRoute: typeof AnimeSearchRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  AnimeCompleteAnimePageRoute: typeof AnimeCompleteAnimePageRoute
  AnimeDetailSlugRoute: typeof AnimeDetailSlugRoute
  AnimeOngoingAnimePageRoute: typeof AnimeOngoingAnimePageRoute
  AnimeWatchSlugRoute: typeof AnimeWatchSlugRoute
}

const AnimeRouteChildren: AnimeRouteChildren = {
  AnimeSearchRoute: AnimeSearchRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  AnimeCompleteAnimePageRoute: AnimeCompleteAnimePageRoute,
  AnimeDetailSlugRoute: AnimeDetailSlugRoute,
  AnimeOngoingAnimePageRoute: AnimeOngoingAnimePageRoute,
  AnimeWatchSlugRoute: AnimeWatchSlugRoute,
}

const AnimeRouteWithChildren = AnimeRoute._addFileChildren(AnimeRouteChildren)

interface Anime2RouteChildren {
  Anime2SearchRoute: typeof Anime2SearchRoute
  Anime2IndexRoute: typeof Anime2IndexRoute
  Anime2CompleteAnimePageRoute: typeof Anime2CompleteAnimePageRoute
  Anime2DetailSlugRoute: typeof Anime2DetailSlugRoute
  Anime2OngoingAnimePageRoute: typeof Anime2OngoingAnimePageRoute
  Anime2WatchSlugRoute: typeof Anime2WatchSlugRoute
}

const Anime2RouteChildren: Anime2RouteChildren = {
  Anime2SearchRoute: Anime2SearchRoute,
  Anime2IndexRoute: Anime2IndexRoute,
  Anime2CompleteAnimePageRoute: Anime2CompleteAnimePageRoute,
  Anime2DetailSlugRoute: Anime2DetailSlugRoute,
  Anime2OngoingAnimePageRoute: Anime2OngoingAnimePageRoute,
  Anime2WatchSlugRoute: Anime2WatchSlugRoute,
}

const Anime2RouteWithChildren =
  Anime2Route._addFileChildren(Anime2RouteChildren)

interface KomikRouteChildren {
  KomikSearchRoute: typeof KomikSearchRoute
  KomikIndexRoute: typeof KomikIndexRoute
  KomikCategoryPageRoute: typeof KomikCategoryPageRoute
  KomikChapterSlugRoute: typeof KomikChapterSlugRoute
  KomikDetailSlugRoute: typeof KomikDetailSlugRoute
}

const KomikRouteChildren: KomikRouteChildren = {
  KomikSearchRoute: KomikSearchRoute,
  KomikIndexRoute: KomikIndexRoute,
  KomikCategoryPageRoute: KomikCategoryPageRoute,
  KomikChapterSlugRoute: KomikChapterSlugRoute,
  KomikDetailSlugRoute: KomikDetailSlugRoute,
}

const KomikRouteWithChildren = KomikRoute._addFileChildren(KomikRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnimeRoute: AnimeRouteWithChildren,
  Anime2Route: Anime2RouteWithChildren,
  KomikRoute: KomikRouteWithChildren,
  ProjectRoute: ProjectRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
